# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ggmdDqAG_NoQQ6v2sHttugwgZC8ZL1Yx
"""

import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize, sent_tokenize, regexp_tokenize

text = "NLTK is a powerful library for natural language processing. It provides various tools for text analysis."

words = word_tokenize(text)
print("Word Tokenization:")
print(words)

sentences = sent_tokenize(text)
print("\nSentence Tokenization:")
print(sentences)

pattern = r'\b[A-Z][a-z]*\b'
regexp_tokens = regexp_tokenize(text, pattern)
print("\nRegExp Tokenization:")
print(regexp_tokens)

